<?php
/**
 * Copyright © Eriocnemis, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="actions eriocnemis-email-actions">
    <p class="hidden" id="<?= $block->getHtmlId() ?>_result"></p>
    <button class="eriocnemis-email-send" type="button" id="<?= $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
