<?php
/**
 * Copyright © Eriocnemis, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Message Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                        <tr>
                            <th><?= $block->escapeHtml(__('Subject')) ?></th>
                            <td><?= $block->escapeHtml($block->getSubject()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Recipient Email')) ?></th>
                            <td><?= /* @noEscape */ $block->getRecipient() ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Carbon Copy')) ?></th>
                            <td><?= /* @noEscape */ $block->getCc() ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Blind Carbon Copy')) ?></th>
                            <td><?= /* @noEscape */ $block->getBcc() ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Sender')) ?></th>
                            <td><?= $block->escapeHtml($block->getSender()) ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Sending Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody> 
                        <tr>
                            <th><?= $block->escapeHtml(__('Sending Time')) ?></th>
                            <td><?= $block->escapeHtml($block->getCreatedAt()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Sending Duration')) ?></th>
                            <td><?= $block->escapeHtml($block->getDuration()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Transport')) ?></th>
                            <td><?= $block->escapeHtml($block->getTransport()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Status')) ?></th>
                            <td><?= $block->escapeHtml($block->getStatus()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Error Message')) ?></th>
                            <td><?= $block->escapeHtml($block->getError()) ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="admin__page-section order-view-account-information">
    <div id="message-body"><?= /* @noEscape */ $block->getBody() ?></div>
</section>
